# name: Demo to create automatic PR

# on:
#   pull_request:
#     types:
#       - opened
#     branches:
#       - 'whitelabel/**'

name: "[chore] Merge pull request from v99 to whitelabels"

on:
  push:
    branches:
      - "v99"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr-on-push:
    name: "Merge pull request from v99 to whitelabels"
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
     - uses: actions/checkout@v1
     - name: My first step
       uses: ./.github/actions/pr-whitelabel
       
      - name: Run auto-merge-action
        id: run-auto-merge-action
        uses: ./.github/actions/pr-whitelabel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base: whitelabel/CachorroBank
          head: v99

      - name: Run auto-merge-action
        id: run-auto-merge-action-2
        uses: ./.github/actions/pr-whitelabel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base: whitelabel/testing
          head: v99
