name: Push File

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          #   API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_folder: "*"
          destination_repo: "Fit-Iuri/actions-paste"
          destination_base_branch: "v99"
          destination_head_branch: "v99"
          user_email: "iuri.mendes@fitbank.com.br"
          user_name: "Fit-Iuri"
          helper: '!f() { test "$1" = get && echo "password=$(cat $HOME/.secret)"; }; f'
