name: Push File

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: Fit-Iuri/action-pr-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "*"
          destination-github-username: "Fit-Iuri"
          destination-repository-name: "actions-paste"
          user-email: iuri.mendes@fitbank.com.br
          target-branch: v99
