name: pushWhitelabels

on:
  push:
    branches: [whitelabel/BancoZap]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: bancozap
          destination-github-username: Fit-Iuri
          destination-repository-name: bancozap
          user-email: iuri.mendes@fitbank.com.br
          commit-message: Copiando ORIGIN_COMMIT para $GITHUB_REF
          target-branch: main
